apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vhbps9r3y-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vhbps9r3y-python 
  name: vhbps9r3y-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vhbps9r3y-python 
